config/routes.rb
Rails.application.routes.draw do
  get 'products/show'
  get 'categories/index'
  get 'categories/show'
  get 'sessions/index'
  get 'sessions/new'
  get 'home/index'
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

      resources :categories, only:[:index, :show]
      resources :products, only:[:show]
      post 'show_category', to: 'categories#show_category', as: 'show_category'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # enum role: { buyer: 0, seller: 1}
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :role])  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end


  # def show_category
  #   @category = Category.find(params[:id])
  #   @products = @category.products
  # end
  

  def show
@category = Category.find(params[:id])
  @products = @category.products
  end
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/categories/index.html.erb
<!-- app/views/categories/index.html.erb -->

<h1>Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category), remote: true%></li>
  <% end %>
</ul>

 <%# <h1>Categories</h1>
# <%= form_tag categories_show_path , method: :get do %>
<%# <%= select_tag :category, options_for_select(@categories.map { |category| [category.name, category.id] }), prompt: 'Select a category' %>
  <%# <%= submit_tag 'Filter', class: 'btn btn-primary' %>
<%# <% end %>
<%# <h1>Categories</h1> %>



<%# <script>
  function submitCategoryForm() {
    document.getElementById('category-form').submit();
  }
</script> %>


<div id="products-container"></div>

app/views/categories/show.html.erb
<h2>Show Product</h2>
<% @products.each do |product| %>
  <p>Name: <%= product.bame %></p>
<% end %>

app/views/home/index.html.erb
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>E-commerce store</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"></a>
          </li>
          <li>
<%= link_to "Categories", categories_path, class: 'btn btn-primary' %>
<%# <%= form_tag categories_show_path, method: :get, id: 'category-form' do %>
  <%# <div class="form-group"> %>
    <%# <%= label_tag "category", "Select a category:" %>
    <%# <%= select_tag :category, options_for_select(@categories.map { |category| [category.name, category.id] }, prompt: 'Select a category'), class: 'form-control' %>
  <%# </div> %>
  <%# <%= submit_tag 'Filter', class: 'btn btn-primary' %>
<%# <% end %>
<%# <div class="form-group">
  <%= label_tag "category", "Select a category:" %>
  <%# <%= select_tag :category, options_for_select(@categories.map { |category| [category.name, category.id] }, prompt: 'Select a category'), class: 'form-control' %> 
  <%# <%= link_to 'Filter', categories_show_path, class: 'btn btn-primary' %> 
<%# </div> %>
          </li>
        </ul>
      </div>
        <% if user_signed_in? %>
          <%= "#{current_user.email}"   %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary'%>
          <% else  %>
            <li><%= button_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %></li>
          <%# <li><%= button_to 'Sign up', new_user_registration_path, class: 'btn btn-primary'</li> %>

      <li><%= button_to 'Sign up', new_user_registration_path,method: :get,class: 'btn btn-primary'%></li>
        <% end %>
    
   
  </nav>
</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_products_list.hml.erb
<!-- app/views/products/_products_list.html.erb -->

<h2>Products</h2>
<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.name, product_path(product) %>
      (<%= product.description %>, <%= number_to_currency(product.price) %>)
    </li>
  <% end %>
</ul>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->
<h1>Product Details</h1>
<p>Name: <%= @product.name %></p>
<p>Description: <%= @product.description %></p>
<p>Price: <%= number_to_currency(@product.price) %></p>